import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { localRepo, readManifest, write } from './manifest.mjs';
import { readText } from './targets.mjs';

export const PLACEHOLDER = 'Not summarized yet. Run `dictionary <name>`.';
export const invocable = text => !/^user-invocable:\s*false\s*$/m.test(text.match(/^---\r?\n([\s\S]*?)\r?\n---/)?.[1] || '');
const listed = repo => Object.keys(readManifest(repo).skills).filter(name => invocable(readText(path.join(repo, 'skills', name, 'SKILL.md'))));
const header = '# Skill dictionary\n\nOne line per skill on when to reach for it. Helper skills that cannot be invoked are left out. Regenerated by `pick`, `add`, and `dictionary`. Do not edit by hand.\n';
const instructions = `Below is a SKILL.md for an AI coding assistant. Write ONE sentence, in plain English a non-expert reads at a glance, describing the situation in which a person should reach for this skill. Start with the situation, not with "Use it when". Maximum 30 words. No jargon, no product names unless the skill is about that product, no quotes, no trailing explanation. Reply with the sentence only.

Example of the style: About to write code that crosses a function boundary and want the caller's usage, types, and module shape settled first.`;
const claudeArgs = ['-p', '--no-session-persistence', '--disable-slash-commands', '--tools', '', '--output-format', 'text'];

export function parseDictionary(text) {
  return new Map([...text.matchAll(/^## \/([a-z0-9][a-z0-9_-]*)\nUse it when\n(.+)$/gm)].map(([, name, sentence]) => [name, sentence.trim()]));
}
export function renderDictionary(entries) {
  return header + [...entries].sort(([a], [b]) => a.localeCompare(b)).map(([name, sentence]) => `\n## /${name}\nUse it when\n${sentence}\n`).join('');
}
export function summarize(skillDir, ctx) {
  const name = path.basename(skillDir);
  const input = `${instructions}\n\nSKILL.md:\n${fs.readFileSync(path.join(skillDir, 'SKILL.md'), 'utf8')}`;
  let reply;
  try { reply = execFileSync('claude', claudeArgs, { input, cwd: ctx.cwd, env: ctx.env, encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'] }); }
  catch (error) { throw new Error(`claude failed while summarizing ${name}: ${error.stderr?.toString().trim() || error.message}`); }
  const sentence = reply.replace(/\s+/g, ' ').trim().replace(/^use it when:?\s*/i, '');
  if (!sentence || sentence.length > 400) throw new Error(`Unusable summary for ${name}: ${JSON.stringify(sentence)}`);
  return sentence;
}
export function updateDictionary(repo, ctx, regenerate = []) {
  const file = path.join(repo, 'skill-dictionary.md');
  const before = readText(file), existing = parseDictionary(before), entries = new Map();
  for (const name of listed(repo)) {
    if (!regenerate.includes(name)) { entries.set(name, existing.get(name) || PLACEHOLDER); continue; }
    entries.set(name, (ctx.summarize || summarize)(path.join(repo, 'skills', name), ctx));
    console.log(`Summarized /${name}`);
  }
  const after = renderDictionary(entries);
  if (after !== before) write(file, after);
  return { regenerated: regenerate, dropped: [...existing.keys()].filter(name => !entries.has(name)) };
}
export function unsummarized(repo, names) {
  const current = parseDictionary(readText(path.join(repo, 'skill-dictionary.md')));
  return names.filter(name => (current.get(name) || PLACEHOLDER) === PLACEHOLDER);
}
export default function dictionary(ctx, { names = [], all = false }) {
  const repo = localRepo(ctx), skills = listed(repo);
  const unknown = names.filter(name => !skills.includes(name));
  if (unknown.length) throw new Error(`Not an invocable skill in the manifest: ${unknown.join(', ')}`);
  updateDictionary(repo, ctx, all ? skills : names.length ? names : unsummarized(repo, skills));
}
